// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvXzxv7MJ_tiWao3AHWmK83pzJmmBnNBM',
    appId: '1:759103813559:android:5b7a6e6a928aec680dda32',
    messagingSenderId: '759103813559',
    projectId: 'deliveryapp-b0979',
    databaseURL: '',
    storageBucket: 'deliveryapp-b0979.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvXzxv7MJ_tiWao3AHWmK83pzJmmBnNBM',
    appId: '1:448618578101:ios:0b11ed8263232715ac3efc',
    messagingSenderId: '759103813559',
    projectId: 'deliveryapp-b0979',
    databaseURL: '',
    storageBucket: 'deliveryapp-b0979.appspot.com',
    androidClientId:
        '759103813559-r3vj0q4bvm5jre322ge564se05lhv6ud.apps.googleusercontent.com',
    iosClientId:
        '448618578101-evbjdqq9co9v29pi8jcua8bm7kr4smuu.apps.googleusercontent.com',
    iosBundleId: 'io.flutter.plugins.firebase.messaging',
  );
}
